[tox]
envlist =
    py{312,313,314}-django{52}
    ruff
    docs
    type-checking
skip_missing_interpreters = true

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
DJANGO =
    5.2: django52

[testenv]
extras =
    openapi
    tests
    coverage
deps =
  django52: Django~=5.2.0
  structlog
setenv =
    PYTHONPATH = {toxinidir}
    PGPASSWORD =
passenv =
    PGPORT
    DB_USER
    DB_HOST
    DB_PASSWORD
commands =
  pytest tests \
   --cov --cov-report xml \
   {posargs}

[testenv:ruff]
extras = tests
skipsdist = True
commands =
    ruff check --output-format=github .
    ruff format --check

[testenv:docs]
basepython=python
changedir=docs
skipsdist=true
extras =
    docs
    tests
allowlist_externals = make
commands=
    make SPHINXOPTS="-W" html
    make linkcheck

[testenv:type-checking]
description = Run static type checking with Pyright
deps = .[type-checking,tests]
skipsdist = True
commands = pyright --project pyright.pyproject.toml
