# Generated by Django 2.2.27 on 2022-03-10 16:12

import django.db.models.deletion
from django.db import migrations, models

import django_loose_fk.constraints
import django_loose_fk.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakObject2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extern_zaak", models.URLField(blank=True)),
                (
                    "zaak",
                    django_loose_fk.fields.FkOrURLField(
                        blank=False,
                        fk_field="_zaak",
                        null=False,
                        url_field="extern_zaak",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="b",
            name="local_type_or_remote_type_filled",
        ),
        migrations.RemoveConstraint(
            model_name="c",
            name="local_b_or_remote_b_filled",
        ),
        migrations.RemoveConstraint(
            model_name="dummymodel",
            name="_zaaktype1_or_extern_zaaktype1_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaak",
            name="_zaaktype_or_extern_zaaktype_filled",
        ),
        migrations.RemoveConstraint(
            model_name="zaakobject",
            name="_zaak_or_extern_zaak_filled",
        ),
        migrations.AddConstraint(
            model_name="b",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="testapp",
                fk_field="local_type",
                model_name="b",
                url_field="remote_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="c",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="testapp",
                fk_field="local_b",
                model_name="c",
                url_field="remote_b",
            ),
        ),
        migrations.AddConstraint(
            model_name="dummymodel",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="testapp",
                fk_field="_zaaktype1",
                model_name="dummymodel",
                url_field="extern_zaaktype1",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaak",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="testapp",
                fk_field="_zaaktype",
                model_name="zaak",
                url_field="extern_zaaktype",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaakobject",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="testapp",
                fk_field="_zaak",
                model_name="zaakobject",
                url_field="extern_zaak",
            ),
        ),
        migrations.AddField(
            model_name="zaakobject2",
            name="_zaak",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="testapp.Zaak",
            ),
        ),
        migrations.AddConstraint(
            model_name="zaakobject2",
            constraint=django_loose_fk.constraints.FkOrURLFieldConstraint(
                app_label="testapp",
                fk_field="_zaak",
                model_name="zaakobject2",
                url_field="extern_zaak",
            ),
        ),
    ]
