# Generated by Django 2.2.4 on 2019-08-08 16:47

import django.db.models.deletion
from django.db import migrations, models

import django_loose_fk.fields


class Migration(migrations.Migration):

    dependencies = [("testapp", "0002_auto_20190808_0805")]

    operations = [
        migrations.CreateModel(
            name="C",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_b", models.URLField(blank=True)),
                (
                    "b",
                    django_loose_fk.fields.FkOrURLField(
                        fk_field="local_b", url_field="remote_b"
                    ),
                ),
                (
                    "local_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="testapp.B",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="c",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        models.Q(_negated=True, local_b__isnull=True), ("remote_b", "")
                    ),
                    models.Q(
                        ("local_b__isnull", True), models.Q(_negated=True, remote_b="")
                    ),
                    _connector="OR",
                ),
                name="local_b_or_remote_b_filled",
            ),
        ),
    ]
