# Generated by Django 5.0.4 on 2024-04-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0003_auto_20230705_0917"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaakObjectFk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "zaak_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="testapp.zaakobject",
                    ),
                ),
            ],
        ),
    ]
