# Generated by Django 2.2.4 on 2020-07-02 05:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0004_auto_20191127_0536"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeb", name="uuid", field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
